src/dukop/apps/calendar/urls.py
from django.urls import path

from . import views


app_name = 'calendar'

urlpatterns = [
    path("", views.index),
    path("event/create", views.EventCreate.as_view(), name="event_create"),
]

src/dukop/apps/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logged_out.html"), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(template_name="users/password_change_form.html"), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(template_name="users/password_reset_form.html"), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

src/dukop/conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls)]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

src/dukop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("users/", include("dukop.apps.users.urls")),
    path("", include("dukop.apps.calendar.urls")),
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

src/dukop/apps/calendar/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Event(models.Model):

    name = models.CharField(
        max_length=255,
        verbose_name=_("name"),
    )
    description = models.TextField(
        blank=True,
        verbose_name=_("description"),
    )

    slug = models.SlugField(
        null=True,
        blank=True,
        verbose_name=_("slug"),
        help_text=_("The part of a URL that is displayed in dukop.dk/event/<slug>/"),
    )

    host = models.ForeignKey(
        'users.Group',
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name='events',
        help_text=_("A group may host an event and be displayed as the author of the event text.")
    )

    featured = models.BooleanField(default=False)
    published = models.BooleanField(default=False)

    link1 = models.URLField(blank=True, null=True)
    link2 = models.URLField(blank=True, null=True)
    link3 = models.URLField(blank=True, null=True)
    link4 = models.URLField(blank=True, null=True)
    link5 = models.URLField(blank=True, null=True)

    is_cancelled = models.BooleanField(default=False)
    show_nb = models.BooleanField(default=False)

    venue_name = models.CharField(
        max_length=255,
        verbose_name=_("venue name"),
        blank=True,
        null=True,
        help_text=_("If left blank, will be copied from host group"),
    )
    street = models.CharField(
        max_length=255,
        verbose_name=_("street"),
        blank=True,
        null=True,
        help_text=_("If left blank, will be copied from host group"),
    )
    city = models.CharField(
        max_length=255,
        verbose_name=_("city"),
        blank=True,
        null=True,
        help_text=_("If left blank, will be copied from host group"),
    )
    zip_code = models.CharField(
        verbose_name=_("zip code"),
        blank=True,
        null=True,
        max_length=16,
        help_text=_("If left blank, will be copied from host group"),
    )

    interval = models.ForeignKey(
        'Interval',
        on_delete=models.PROTECT,
        help_text=_("Repeats the event automatically at some interval"),
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    owner_user = models.ForeignKey(
        'users.User',
        verbose_name=_("owner (user)"),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='owned_events',
    )
    owner_group = models.ForeignKey(
        'users.Group',
        verbose_name=_("owner (group)"),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='owned_events',
    )

    edit_secret = models.CharField(
        max_length=255,
        verbose_name=_("edit secret"),
        blank=True,
        null=True,
        editable=False,
    )

    view_secret = models.CharField(
        max_length=255,
        verbose_name=_("view secret"),
        blank=True,
        null=True,
        editable=False,
    )

    class Meta:
        verbose_name = _("Event")


class EventTime(models.Model):
    """
    Allows an event to take place at many different times
    """

    event = models.ForeignKey(Event, related_name='times', on_delete=models.CASCADE)
    start = models.DateTimeField(
        verbose_name=_("start"),
    )
    end = models.DateTimeField(
        verbose_name=_("end"),
    )
    comment = models.CharField(
        max_length=255,
        verbose_name=_("comment"),
        help_text=_("Leave blank and nothing will be shown to readers"),
        blank=True,
        null=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Event time")
        ordering = ('start', 'end')


class EventUpdate(models.Model):

    description = models.TextField(
        blank=True,
        verbose_name=_("description"),
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Event time")
        ordering = ('created',)


class EventImage(models.Model):

    event = models.ForeignKey(Event, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Allowed formats: JPEG, PNG, GIF. Please upload high resolution (>1000 pixels wide).")
    )
    priority = models.PositiveSmallIntegerField(
        default=0,
        help_text=_("0=first, 1=second etc.")
    )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('priority',)


class Interval(models.Model):

    weekday = models.ForeignKey('Weekday', on_delete=models.CASCADE)

    every_week = models.BooleanField(default=False)
    first_week_of_month = models.BooleanField(default=False)
    second_week_of_month = models.BooleanField(default=False)
    third_week_of_month = models.BooleanField(default=False)
    last_week_of_month = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


class Weekday(models.Model):

    name = models.CharField(
        max_length=255,
        verbose_name=_("name"),
    )
    number = models.PositiveSmallIntegerField(default=0, unique=True)

src/dukop/apps/users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    """The user manager class."""

    def create_user(self, password: str = None, **kwargs):
        user = self.model(**kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, password: str, **kwargs):
        user = self.create_user(password=password, **kwargs)
        user.is_staff = True
        user.is_superuser = True
        user.save(update_fields=['is_staff', 'is_superuser'])
        return user


class User(PermissionsMixin, AbstractBaseUser):

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'

    objects = UserManager()

    nick = models.CharField(max_length=60, null=True, blank=True)
    email = models.EmailField(
        unique=True,
        verbose_name=_('E-Mail'),
        help_text=_(
            'Your email address will be used for password resets and notification about your event/submissions.'
        ),
    )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    def __str__(self) -> str:
        """Use a useful string representation."""
        return self.get_display_name()

    def get_display_name(self) -> str:
        return self.nick if self.nick else str(_('Unnamed user'))

    class Meta:
        verbose_name = _("User")


class Group(models.Model):

    name = models.CharField(
        max_length=255,
        verbose_name=_("name"),
    )
    members = models.ManyToManyField(User, related_name='dukop_groups')

    is_restricted = models.BooleanField(
        default=False,
        help_text=_("Do not allow others to add events to this group"),
    )

    owner_email = models.EmailField(blank=True, null=True)

    link1 = models.URLField(blank=True, null=True)
    link2 = models.URLField(blank=True, null=True)
    link3 = models.URLField(blank=True, null=True)

    street = models.CharField(
        max_length=255,
        verbose_name=_("street"),
        blank=True,
        null=True,
    )
    city = models.CharField(
        max_length=255,
        verbose_name=_("city"),
        blank=True,
        null=True,
    )
    zip_code = models.CharField(
        verbose_name=_("zip code"),
        blank=True,
        null=True,
        max_length=16,
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Group")

src/dukop/apps/calendar/forms.py
from django import forms
from django.forms.formsets import formset_factory

from . import models


class EventForm(forms.ModelForm):

    class Meta:
        model = models.Event
        fields = ('name', 'description', 'host', 'venue_name', 'street', 'zip_code', 'city')


class EventTimeForm(forms.ModelForm):

    class Meta:
        model = models.EventTime
        fields = ('start', 'end')


class EventImageForm(forms.ModelForm):

    is_cover = forms.BooleanField()

    def save(self, commit=True):
        # A very naive implementation of priority, just sets '0' on the
        # cover image
        image = forms.ModelForm.save(self, commit=False)
        if self.cleaned_data['is_cover']:
            image.priority = 0
        else:
            image.priority = 1
        return image

    class Meta:
        model = models.EventImage
        fields = ('image',)


EventTimeFormSet = formset_factory(EventTimeForm, extra=5, max_num=5)
EventImageFormSet = formset_factory(EventImageForm, extra=5, max_num=5)

src/dukop/apps/calendar/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView

from . import forms
from . import models


def index(request):
    return render(request, "calendar/index.html")


class EventCreate(CreateView):

    template_name = 'calendar/event/create.html'
    model = models.Event
    form_class = forms.EventForm

    def get_context_data(self, **kwargs):
        c = CreateView.get_context_data(self, **kwargs)
        c['times'] = forms.EventTimeFormSet(prefix='times')
        c['images'] = forms.EventImageFormSet(prefix='images')
        return c

src/dukop/apps/users/views.py
from django.contrib.auth import views as auth_views
from django.urls.base import reverse_lazy


class PasswordResetView(auth_views.PasswordResetView):
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy('users:password_reset_complete')


class PasswordChangeView(auth_views.PasswordChangeView):
    success_url = reverse_lazy('users:password_change_done')

src/dukop/templates/base.html
{% load i18n static compress %}<!DOCTYPE html>
<html>
<head>
<title>Duk Op</title>
<meta name="viewport" content="width=device-width, minimum-scale=1.0,initial-scale=1.0" />
<!-- Shortcut icons (favicon) -->
<link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
<link rel="apple-touch-icon" href="{% static 'img/favicon.png' %}">

    <meta property="og:url" content="https://www.dukop.dk/">
    <meta property="og:title" content="Duk dig ikke - Duk Op!">
    <meta property="og:description" content="DukOp er vores fælles guide til, hvad der sker i København og omegn, hvad enten du leder efter demonstrationer, koncerter, fester, møder, folkekøkkener, havedage, workshops, kunst- og filmfremvisninger, mv..">
    <meta property="og:image" content="{% static 'img/social_media.jpg' %}">
    <meta property="og:site_name" content="Duk Op">
    <meta property="og:locale" content="da_DK">

    {% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static 'css/application.scss' %}">
    {% endcompress %}
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="u/r1XnjQgRo5bxwz7fZNl98KN+p2Bjc0SRu2LcXwVwdlnhwE9tG9ps1/fqKCDkpqrml+c8zI6MIzrXN7blbBGw==" />
</head>
<body>
<div class="lock-body" id="js-lock-body">

    <header>
        <div class="page-container">
            <div class="header">
                <div class="header__logo">
                    <a href="/?locale=da">
                        <img src="{% static 'img/moon_logo.png' %}" alt="Moon logo" />

</a>                </div>
                <div class="header__burger js-toggle" data-element="js-controls">
                    <div></div>
                    <div></div>
                    <div></div>
                </div>

                {% if user.is_authenticated %}

                  <a class="header__link" href="{% url 'calendar:event_create' %}">{% trans "New event" %}</a>
                  <a class="header__link" href="{% url "users:logout" %}">{% trans "Log out" %}</a>

                {% else %}

                  <a class="header__link" href="{% url "users:login" %}">{% trans "Log in" %}</a>

                {% endif %}

            </div>
        </div>
    </header>

{% block listContent %}

<div class="card card--static">
        {% block cardContent %}

        {% endblock %}
</div>


{% endblock %}


    <footer>
        <div class="page-container">
            <div class="footer">
                <div class="footer__content">
                    <div class="footer__about">
                        <h2 class="title title--footer">Om os</h2>
                        <p>DukOp er vores fælles guide til, hvad der sker i København og omegn, hvad enten du leder efter demonstrationer, koncerter, fester, møder, folkekøkkener, havedage, workshops, kunst- og filmfremvisninger, mv..</p>
                    </div>
                    <div class="footer__news">
                        <h2 class="title title--footer">Nyt</h2>
                        <div class="news">
                                <a href="/posts/27?locale=da" class="news__link">
                                <div class="news__date">
                                    28.12.18
                                </div>
                                <div class="news__title">
                                    DukOp anbefaler det nye Konfront.dk - Nyheder og Baggrund med mening!
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>